apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: main
  namespace: monitoring
spec:
  replicas: 1
  version: v1.7.1
  externalUrl: https://prometheus-ui.minikube/prometheus
  resources:
    requests:
      memory: 400Mi
---
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: main
  namespace: monitoring
spec:
  replicas: 3
  version: v0.7.1
  externalUrl: https://prometheus-ui.minikube/alertmanager
  resources:
    requests:
      memory: 400Mi
