apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus-web
  namespace: prometheus
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: prometheus.minikube
  - http:
      paths:
      - backend:
          serviceName: prometheus-server
          servicePort: 80
